---
title: "Set up"
---

## Software

**REQUIRED** - We will be using RStudio to analyse the data set. It is recommend you have the following installed: [*RStudio version 1.4*](https://rstudio.com/products/rstudio/download/) or later and [*R version 4.0*](https://www.r-project.org/) or later. Further details on getting started in RStudio [here](http://siobhonlegan.com/research_site/rstudio/).

**Optional** (*not needed for today's workshop*) - We will not be doing the sequence processing steps today but if you did want to do this you will need to download [conda](https://conda.io/projects/conda/en/latest/user-guide/install/index.html) and [QIIME2](https://qiime2.org/).

## Download data

1.  **Raw Sequence data** (*optional*)

The input for analysis is raw sequence data in `.fastq` format. Zipped files come in the format `.fastq.gz`

Rename so `fastq.gz` files are in the format `SAMPLEID_INITIALS_LIBRARYID_L001_R1_001.fastq.gz` (forward) or `SAMPLEID_INITIALS_LIBRARYID_L001_R2_001.fastq.gz` (reverse).

2.  **RData** (*REQUIRED*)

The easiest way to follow along with this tutorial is to download this GitHub repository using either option **1** or **2** below:

1.  Go to <https://github.com/siobhon-egan/BIO510-microbiome> and click on the green **Code** button. Select **Download ZIP**, open/unzip the file. Open the `.Rmd` files in RStudio you will be able to follow along for the data analysis.

2.  Use terminal and clone the GitHub repo.

```
git clone https://github.com/siobhon-egan/BIO510-microbiome.git
```

## Install R packages

You should only need to do this once to install required libraries.

I recommend you run this bit of code line by line.   
As there are dependencies between packages it is best to run them in the order outlines below.

Remember it assumes you have R version 4.0 and RStudio version 1.4.

```r
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
# Phyloseq
BiocManager::install("phyloseq")
# Tidyverse
install.packages("tidyverse")
# Install microbiome utilities
install.packages("devtools")
devtools::install_github("microsud/microbiomeutilities")
# Install MicrobiotaProcess
BiocManager::install("MicrobiotaProcess")
# Install ampvis2
install.packages("remotes")
remotes::install_github("MadsAlbertsen/ampvis2")
# Install vegan
install.packages("vegan")
# Install ggpubr
install.packages("ggpubr")
# R color brewer
install.packages("RColorBrewer")
# agricolae
install.packages("agricolae")
# viridis
install.packages("viridis")
# ape
install.packages("ape")
# DESeq2
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DESeq2")
```

Note I have not included packages that relating to "knitting" the document here. Everything should be executable within the R markdown files by running the code chunks.